version: "3"
services:
  db:
    image: postgres:18
    container_name: indication_db_container
    ports:
    - 5432:5432
    volumes:
    - db-store:/var/lib/postgresql
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'indication'
volumes:
  db-store:
